leonarf/VCA4D

src/components/Skeleton.vue, src/components/StudyOverview.vue, src/components/import/CheckImportedDataStep.vue, src/views/HomeView.vue, src/views/Import.vue
Agrinatura nous font remarquer ([point 1](https://lebasic-my.sharepoint.com/:w:/r/personal/maxime_lebasic_com/_layouts/15/Doc.aspx?sourcedoc=%7B845CE3C2-1A58-4F2F-928B-F5FCDBE425D8%7D&file=Info.System%20Website%20comments%20HY_FL_avec_commentaire_l%25u00e9onard%20OO.docx&action=default&mobileredirect=true)) que le lien de la description n'a pas le bon style
J'en profite pour update tous les liens qui n'ont à mon avis pas un bon style pour un lien
- Couleur bleue lorsque ce lien est au milieu d'un texte sans lien
- target _blank si le lien est externe (/ telechargement d'un pdf) pour éviter que l'utilisateur quitte la plateforme
- Pas d'underline en hover, sauf dans le footer avec les credits: Sinon les liens en gris ne sont pas assez visible
<details><summary>screenshot</summary> …
=> fix: Add link styling to every link which doesn't have one

data/data.json, src/components/comparison/ComparisonHeader.vue, src/components/home/ByCategory.vue, src/components/home/ByContinent.vue, src/components/import/CheckImportedDataStep.vue, src/components/import/SaveOnGithubStep.vue, src/components/study/StudyHeader.vue, src/utils/data.js
Certains produits / comodités affichées doivent etre corrigées
- En ajoutant des noms custom (eg. Oil Palm devient Palm Oil)
- En se basant sur le nom de la commodité plutot que le nom de l'étude
<details><summary>Screenshots</summary>
</details>
- Ajout d'un array `products` dans data.json afin de configurer des nomùs custom sans changer les data des études
- Affichage de ces noms partout
- Dans la home
- Dans le dashboard de comparaison
- Dans les header des pages d'études
=> feat: Use pretty names for products as well

src/components/StudyInclusiveness.vue, src/components/study/inclusiveness/EmploymentDistributionActors.vue, src/components/study/inclusiveness/EmploymentDistributionJobs.vue, src/components/study/inclusiveness/NetOperatingProfit.vue, src/components/study/inclusiveness/NetOperatingProfitPerActor.vue, src/style/main.css
Après avoir fait la refont de Overview & Economic growth, on en profite pour etendre les améliorations (sans que ça soit la  version finale) à la page "Inclusiveness"
<details>
| ----- | ----- | 
| ![image](https://github.com/user-attachments/assets/9bffe5fe-e8f8-4d0c-a573-717e0a3d184f) | ![image](https://github.com/user-attachments/assets/31d65842-06fb-4db7-9052-46e65fff5efa) |
| ![image](https://github.com/user-attachments/assets/51bab8a4-822d-4606-8bcf-9a9807762cc4) | ![image](https://github.com/user-attachments/assets/2ab9b782-3846-4fae-aec0-6d61df75b8e3) |
| ![image](https://github.com/user-attachments/assets/789f46b9-0fb7-4c53-9c01-9ad68ba89f5a) | ![image](https://github.com/user-attachments/assets/4b924044-737b-4a8f-97b5-d1c1be3e4145) |
</details>
Utilisation des …
=> feat: Tweak inclusiveness page

src/components/SankeyChart.vue
See https://madewithvuejs.com/blog/guide-to-error-exception-handling-in-vue-apps This catches every error made in this component's scope or a child component.
=> fix: Ignore sankey lib components error with `onErrorCaptured`

src/App.vue, src/components/home/ByCategory.vue, src/components/home/ByContinent.vue, src/components/home/SubCardsList.vue, src/components/study/StudyMenu.vue, src/router/index.js, src/style/main.css, src/utils/data.js, src/utils/router.js, src/views/Comparison.vue, src/views/StudyView.vue
Resolves #37 
On veut faire une page de comparaison dynamique, en stockant les id des etudes dans l'url
Screenshot
<details>
</details>
- Refactor: Suppression de `:key` sur le router: les composants doivent gerer dynamiquement leurs enfants, et ne pas se baser sur le rechargemenbt complet de l'app a chaque changement
- Un peu de boyscout
- Passage des study ids dans la route.query pour etre lue par la page `Comparison`
- Affichage d'un message "pas détude" si on n'en selectionne aucune
=> refactor: Have study ids stored in the url of the comparison page

data/inland-fisheries-mali/inland-fisheries-mali-social.json, src/components/Modal.vue, src/components/StudiesComparison.vue, src/components/comparison/AddStudiesButton.vue, src/components/comparison/ComparisonEconomicsItem.vue, src/components/comparison/ComparisonEnvironment.vue, src/components/comparison/ComparisonHeader.vue, src/components/comparison/ComparisonSeparator.vue, src/components/comparison/ComparisonSocial.vue, src/components/comparison/ComparisonTitle.vue, src/components/comparison/StudiesListTable.vue, src/images/icons/cross.svg, src/images/icons/plus.svg, src/views/Comparison.vue
#38 
On crée une page de comaraison où on peut modifier la selection des études à comparer
On ajoute donc
- Un bouton pour supprimer des études de la comparaison
- Un bouton pour selectionner plus d'études
<details><summary>Screenshot</summary>
[Screencast from 2024-07-26 09-36-27.webm](https://github.com/user-attachments/assets/0c49c38b-a80a-42b9-b1a8-ea971e10c86e)
</details>
- Qques fix opportunistes
- Ajout du bouton "remove" qui update `route.query.studies`
- Ajout du bouton `Add studies` qui ouvre une modal avec un tableau
- Ajout du bouton dans une nouvelle colonne du tableau (J'ai essayer en le mettant en dehors du `table`, et j'y ai passé ma journée :sob:)
- Ajout d'un composant Modal simple
- Ajout du composant de tableau selecteur d'études (:construction: à affiner visuellement …
=> feat: Add study selector for comparison page

src/components/StudiesComparison.vue, src/components/charts/DataTable.vue, src/components/comparison/ComparisonHeader.vue, src/components/study/inclusiveness/ShareOfFarmPrice.vue, src/views/Comparison.vue
Après avoir générifié `DataTable` dans https://github.com/leonarf/VCA4D/pull/48, je modifie son style
| avant | après |
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/e97dc59d-2eb8-4dc7-bb85-85a1c947bfae) | ![image](https://github.com/user-attachments/assets/79dbc3b6-88a3-4e43-8844-0582b4d636ce) |
Quelques différence notables avec le [Figma](https://www.figma.com/design/6mmWHxGGyAEAvgSUm5dGFD/VCA4D?node-id=623-1688&t=ibKIDdrVxdE8rYwt-4)
- Pas de texte "sort" sur le header, j'ai gardé les fleches de TableLite.
- Pas de blur bleu en dessous du tableau pour indiquer qu'on est pas en bas (ajouté à https://github.com/leonarf/VCA4D/issues/49)
- Scrollbar pas exactement bleue (mais de la couleur du browser) (ajouté à https://github.com/leonarf/VCA4D/issues/49)
- Addition …
=> feat: Update table style

src/components/StudiesComparison.vue, src/components/StudyInclusiveness.vue, src/components/charts/DataTable.vue, src/components/charts/TableauDeDonnées.vue, src/components/comparison/ComparisonHeader.vue, src/components/comparison/StudiesListTable.vue, src/components/study/inclusiveness/ShareOfFarmPrice.vue, src/views/Comparison.vue
Dans #38, j'ajoute un tableau dans la page de comparaison. Hors, il en existe déjà un dans la page d'Inclusiveness, codé avec le générique `TableaDeDonnées`.
Cette PR refactor ce composant pour l'adapter aux 2 use case
- Composition API + Anglais
- Utilisation du slot-mode, car `hasCheckbox` ne permet pas d'avoir des rows deja selected
- Modification de l'interface du composant pour données toute la largeur d'actions aux utilisateurs du composant
- Utilisation de `doSearch` pour trier les données. Le sort "natif" ne marchant pas avec le slot-mode
=> refactor(38): Generify TableauDeDonnées

src/components/study/ComparisonLink.vue, src/components/study/StudyHeader.vue, src/images/icons/balance.svg, src/utils/data/json.js
Resolves #46 
On veut simplifier la comparaison d'une étude avec celles qui ont le meme produit/pays
On ajoute donc des liens vers les bonnes pages de comparaison dans le header
:construction: J'ai pris l'initiative sur le design, et cela passera par une review de Gaspard dès demain
| avant | après |
| - | - |
| ![image](https://github.com/user-attachments/assets/83f32003-85d5-469e-99b5-3e8a3a6d540f) | ![image](https://github.com/user-attachments/assets/fcf6dd4a-f271-4f73-b76e-b0624ffdc351) | 
- Ajout d'un composant `ComparisonLink` qui encapsule la récuperation des bonnes infos et le logo
- Integration de ce composant dans `StudyHeader`
=> feat: Add links to comparison pages from study header

index.html, package-lock.json, src/App.vue, src/components/pdf/PdfReader.vue, src/router/index.js, src/style/main.css, src/views/HomeView.vue
Les drapeaux ne se chargeaient pas toujours.
Le problème étant qu'on chargeait le css dans les fichiers `html` vers lesquels on guide l'app (eg `index.html`). Mais aucun html (mis a part `index.html`) ne chargeait ce css
- Chargement du css resource dans `App.vue`
- Boyscout: Amélioration de la taille des chunks quand on `build` l'app. Notamment, le PDF Reader fait 3 MB et n'est pas toujours necessaire.
=> refactor: reduce chunks size + ensure flags are loading 

src/components/home/ByCategories.vue, src/components/home/ByContinents.vue, src/components/home/Section.vue, src/views/HomeView.vue
On redesigne un peu la sectiond des filtres dans la home pour 
- Avoir un vrai highlight sur cette section
- Ajouter un lien vers la page de comparaison
| - | - |
| ![image](https://github.com/user-attachments/assets/5e129b77-cda2-4a08-a3f7-9acaeb6796ba) |![image](https://github.com/user-attachments/assets/ecfe891f-460a-4b54-a441-78b07ca3432f) |
=> feat: Format a real section for the filters

data/data.json, src/components/comparison/StudiesListTable.vue, src/components/home/ByContinent.vue, src/components/home/Card.vue, src/components/import/SaveOnGithubStep.vue, src/components/study/ComparisonLink.vue, src/components/study/StudyHeader.vue
Resolves #65 
A plusieurs endroits du code, on "capitalize" les noms de produits/pays. Hors
- `_.capitalize` et la class tailwind `capitalize` n'ont pas le meme effet (le premier ne met en upppercase que la premiere lettre de la string, le 2e de tous les mots)
- On risque alors de déformer le nom des pays, bien rentré dans les json d'étude
- On arrete de `capitalize` à tout va
- On fige le pretty name des product avec une Majuscule au début
- On `lowerCase` la seule fois ou un produit est dans une phrase (les pays sont toujours avec des majuscules)
=> fix: Don't capitalize pretty names

src/charts/charts.js, src/components/study/environment/ImpactDataviz.vue, src/utils/colors.js
Relié à #61 
Les graphes coté environnement ne sont pas beaux
On utilise les memes couleurs par défaut que dans les pages economiques
|-|-|
| ![image](https://github.com/user-attachments/assets/72b447c7-9735-4f73-83e6-2b69611ee2ce) | ![image](https://github.com/user-attachments/assets/c48ea07d-582f-4ad2-b916-56774a0eb4b3) |
=> feat: Use normal graph colors for environment graphs

src/components/StudyEnvironment.vue, src/components/charts/DataTable.vue, src/components/study/RadioInput.vue, src/style/main.css
Resolves: #62
Dans la page d'étude ACV, le selecteur d'unité / de scope n'est pas très clair.
Sur proposition de gaspard, on l'améliore, en ajoutant des explications
| Avant | Après | 
|-|-|
| ![image](https://github.com/user-attachments/assets/5fa144f8-857a-48da-90b9-ab269ead2896) | ![image](https://github.com/user-attachments/assets/81297650-1af1-45fc-b628-d025a41012c2) |
- Ajout d'un composant de selection d'option via RadioButton, pour l'utiliser à la place des boutons actuels
- Ajout de titres et sous-titres
- Styling
=> feat(62): Refactor unit settings in study's ACV page

src/charts/charts.js, src/components/study/economic-growth/AddedValue.vue
Resolves #73 
Dans un ring chart, certains labels ne mettent a la ligne que certaines lettres
De plus, certains labels ne sont pas montrés si la valeur est trop faible (cf "Financial institutions")
| - | - |
| ![image](https://github.com/user-attachments/assets/a7241476-958d-478e-85ef-93155893ed54) | ![image](https://github.com/user-attachments/assets/74855815-c8ee-4178-9127-51f982783ef4) |
- Définition d'une largeur des labels
- Plsu de largeur pour le graphique entier
=> fix(73): Allow labels to expand

src/components/study/CurrencySelector.vue, src/components/study/StudyHeader.vue, src/components/study/StudyMenu.vue, src/style/main.css, src/views/StudyView.vue
Resolves #58 
On veut pouvoir changer la devise depuis le header de l'étude, afin de rassembler les 2 endroits ou on parle de devise
- On met le selecteur dans le header
- On affiche l'info de devise locale lorsqu'elle est choisie
| - | - |
| [Screencast from 2024-08-19 17-07-51.webm](https://github.com/user-attachments/assets/4bc14b70-2b5f-4e61-bf13-84111406ccef) | [Screencast from 2024-08-19 17-08-15.webm](https://github.com/user-attachments/assets/f2b93add-2c7f-45b6-b173-68fa95a807bd)|
- Extraction du selecteur
- Déplacement dans le header (branchement de la logique)
- Style pour s'inclure au header
- Ajout de l'info "Converted from ..." dans le sous-titre
=> feat(58): Include currency selector in study header

src/components/StudyOverview.vue, src/components/comparison/ComparisonHeader.vue, src/components/home/ByCategories.vue, src/components/home/ByCategory.vue, src/components/home/ByContinent.vue, src/components/home/ByContinents.vue, src/utils/router.js, src/views/HomeView.vue, src/views/StudyView.vue
A chaque fois qu'on navigue depuis le "Functional analysis" vers une page, on perd l'info de currency de l'url
- Utilisation d'un evenement emit par StudyOverview afin de naviguer toujours avec `selectView` de `StudyView.vue`
- Petit refactor de `getLink` pour eviter des props inutiles dans la Home
=> fix(58): Keep currency in url query when navigating with section descriptions in overview

src/components/study/CurrencySelector.vue, src/views/StudyView.vue
Resolves #80 
Lorsqu'une currency n'est pas convertible, le selecteur ne s'affiche pas quand on a en cache (ou en url) USD / EUR
On force à LOCAL si la currency locale n'est pas supportée.
=> fix: Default to local currency when we cannot convert it

src/components/StudiesComparison.vue, src/components/comparison/ComparisonExpandableRow.vue, src/components/comparison/ComparisonRow.vue
Issue: #67
On veut afficher plus de données dans la page de comparaison grace a un menu déroulant
- Le ratio Benefice/couts (avec un dropdown par `stage`
- On veut également avoir des dropdown avec tous les sous-aspects sociaux
- [85](https://github.com/leonarf/VCA4D/pull/85) Création d'un composant pour le dropdown
- À merger simulatanément
- [88](https://github.com/leonarf/VCA4D/pull/88) Ajout des données
- :dart: **Cette PR**: Améliorer le style de ces dropdowns
| - | - |
| [Screencast from 2024-08-21 16-56-25.webm](https://github.com/user-attachments/assets/53bc2dbe-67f6-4b0d-a8fb-3509c365924d) | [Screencast from 2024-08-21 16-54-13.webm](https://github.com/user-attachments/assets/b95cb3c3-06ba-42c9-86e3-2d713443e0dd) |
- Changements des couleurs de background 
- …
=> feat(67): Better style for the expandable rows

src/components/StudiesComparison.vue, src/components/comparison/ComparisonEconomics.vue, src/components/comparison/ComparisonExpandableRow.vue, src/components/comparison/ComparisonRow.vue, src/utils/data/metrics/eco/returnOnInvestment.js, src/utils/data/metrics/index.js
Issue: #67
Suite à #88 , on calculait des métrique eco au chargement d'une étude, meme si elle n'avait pas de données éco ! Cela fait crasher la popup de la page de comparaison.
- Ne pas populate les métriques `eco` si `ecoData` n'est pas défini
- [Bonus] Ne pas afficher le dropdown s'il n'y a aucune sous-donnée
- [Bonus] Un peu de styling en plus pour peaufiner le dropdown
=> fix(67): Don't compute eco metrics if there's no ecoData

src/components/study/StudyHeader.vue, src/components/typography/InfoTooltip.vue, src/components/typography/NiceMetric.vue
Resolves #74
On ajoute un tooltip expliquant qu'on utilise les taux de la banque mondiale
- Factorisation du tooltip sur une icone `?` (utilisé dans `NiceMetric`)
- Ajout dans le Conversion Selector
=> feat(74): Display conversion info when converting the local currency

src/components/StudiesComparison.vue, src/components/StudyEconomicGrowth.vue, src/components/comparison/ComparisonEconomics.vue, src/components/comparison/ComparisonExpandableRow.vue, src/components/comparison/ComparisonRow.vue, src/components/comparison/ComparisonTitle.vue, src/components/study/economic-growth/BenefitCostRatio.vue, src/utils/data/metrics/eco/benefitCostRatio.js, src/utils/data/metrics/eco/returnOnInvestment.js, src/utils/data/metrics/index.js
Resolves #67
On veut afficher plus de données dans la page de comparaison grace a un menu déroulant
- Le ratio Benefice/couts (avec un dropdown par `stage`
- On veut également avoir des dropdown avec tous les sous-aspects sociaux
Screenshot (style non final)
[Screencast from 2024-08-21 15-40-03.webm](https://github.com/user-attachments/assets/bf54eb05-8a43-4eec-b40f-14a91f0ba251)
- [85](https://github.com/leonarf/VCA4D/pull/85) Création d'un composant pour le dropdown
- À merger simulatanément
- [88](https://github.com/leonarf/VCA4D/pull/88): Ajout des données
- [89](https://github.com/leonarf/VCA4D/pull/89) Améliorer le style de ces dropdowns
- :dart: **Cette PR**: Quelques améliorations de style
- Quelques améliorations de style
- Update de la marge
- Mise en gras au hover du parent-row …
=> feedback(67): Handle Gaspard's feedback

src/components/study/CurrencySelector.vue, src/components/study/StudyHeader.vue, src/views/StudyView.vue
Resolves #86
Lorsqu'on a une étude qui a pour devise locale une des 2 génériques (USD/EUR), on ne voit pas la devise en allant sur l'url avec `currency=USD`
C'est parce que l'option `USD` n'existe pas dans ce cas la
- Inversion des options possibles: Si la localCurrency est générique, on affiche seulement l'option générique
- De cette manière, si l'user choisit cette option, on met la currency générique dans le localStorage, ce qui permet une meilleure comparaison avec les étude prochainement visitée
- [fix] Si l'url indique LOCAL, on caste l'affichage au générique (problème inverse du ticket, vu qu'on a inversé la logique ci dessus)
- Affichage de `Local currency` en sous-titre dans ce cas ou la locale === la générique
=> fix: Display generic currency if it's the Local one

src/components/StudyOverview.vue, src/components/charts/Sankey.vue
Issue: #68 
On refacto la style pour la section Sakey de l'overview, notamment la selection d'unité
| - | - |
| ![image](https://github.com/user-attachments/assets/71c13b35-a734-44d5-90d0-9f313705d723) | ![image](https://github.com/user-attachments/assets/4eea182d-c259-4353-bfa5-b55e42c6bd5c) |
- Un peu de cleanup
- Utilisation de RadioInput
- Titre en `h2` comme précisé [ici](https://github.com/leonarf/VCA4D/issues/82#issuecomment-2304316570)
=> feat: Better unit selection for Sankey

src/charts/sankey.js, src/charts/sankeyDepth.js
On veut retravailler l'affichage du sankey
La version précédente calculait la profondeur des éléments en les associant à un stage précis. Le problème est que certains stages se lient entre eux, rendant le sankey difficilement lisible.
Dans cette PR, je recalcule la profondeur en fonction du nombre de liens depuis la source
Note: C'est certainement ce que fait déjà echarts par défaut (si on ne passe pas de `depth`, le graphe est similaire). Mais cette PR est une première étape pour mieux afficher la profondeur. J'essayerais ensuite de grouper les noeuds par stage.
- Extraction de la logique de profondeur
- Reecriture de cette logique
=> feat(68): Compute sankey depth by links number from source

src/charts/sankey.js, src/charts/sankeyDepth.js, src/components/charts/Sankey.vue, src/components/study/environment/ImpactDataviz.vue, src/utils/colors.js
Issue #68
On veut améliorer l'affichage du Sankey. Dans cette PR, je
- [tooltip] Refactor la construction des tooltips
- [legend] Ajoute une légende au Sankey.
- On affiche les couleurs des stages.
- J'ajoute une couleur pour le stage `End use` (violet)
- Correction d'un bug de mon algorythme de profondeur
- La profondeur n'était pas calculée si aucun des actors n'était un Producer
- Suppression de l'algo de `nodeGap`, qui empechait de mettre les flux à l'échelle
- :warning: Je change comment on charge la couleur des stages
- Toute couleur non identifiée est maintenant grise
- Celle force les scientifiques à uploader des fichiers avec les  bons labels.
| | Avant | Après | 
| - | - | - |
| Coffee Ecuador | ![image](https://github.com/user-attachments/assets/33213115-4c87-4d85-9b47-e4cc15164 …
=> feat(68): Improve Sankey format (+ color refactor)

src/charts/sankey.js, src/utils/format.js
Resolves: #68
On veut améliorer le sankey. Après quelques retours de Gaspard et Léonard, je
- Ajoute un titre aux tooltips
- Regle l'affichage des nombres (surtout les devises)
| - | - |
| ![image](https://github.com/user-attachments/assets/b463ae72-7358-48ad-af90-805ac9292cff) | ![image](https://github.com/user-attachments/assets/8ee3a829-b39e-41ba-90fe-6656e419b5d8) |
| ![image](https://github.com/user-attachments/assets/3c32e316-b906-4d8a-950c-44c44b17ca49) | ![image](https://github.com/user-attachments/assets/d7ee737d-8bad-484b-b793-d6358f6e1577) |
=> feat(68): Better text format for Sankey

package-lock.json, package.json, src/components/import/CheckImportedDataStep.vue, src/components/import/SaveOnGithubStep.vue, src/utils/currency.js, src/utils/import/eco.js, src/utils/import/environment.js, src/utils/import/generic.js, src/utils/scripts/parseStudyXlsx.js, src/views/Import.vue
Ticket: #53 
On veut changer la facon dont on importe les données
Pour mettre à jour plus rapidement les json (et pour tout bug d'import futur), on construit dans cette PR un script qui calcule les json (d'études, + `data.json`) a partir des xlslx (soirt 1 à 1, soit tous d'un coup)
- :dart **Cette PR**: Création du script
- Réparation de la logique d'import / des données json: L'execution du script modifie plein de données :confused: 
- Modification de l'import des données d'emplois
- Un peu de refacto de la logique de parsing dans `/import` qui retourne les erreur (pour les afficher dans le script)
- Création du script
- Récupération des fichier, et processing
- Ecriture dans les fichier json en local directement
- Option "compute all" pour tout faire en batch
- Ecriture dans `data.json` …
=> feat: Add script to rewrite jsons based on imported xlsx data

src/components/StudyOverview.vue, src/components/study/DownloadSection.vue
Ticket: #82
- Je supprime le lien vers le pdf complet sous la preview du résumé (comme décide ensemble)
- Fix: Je rajoute `target="_blank"` dans le downlad center pour éviter de remplacer la tab actuelle quand on lit des pdf
=> fix(82): feedbacks

eslint.config.js, src/charts/sankey.js, src/components/import/CheckImportedDataStep.vue, src/components/study/economic-growth/BalanceOfTrade.vue, src/components/study/social-sustainability/SocialDetails.vue, src/components/study/social-sustainability/SocialRadar.vue, src/repositories/basicApi.js, src/utils/data/studyData.js, src/utils/data/uploads.js, src/utils/scripts/parseStudyXlsx.js, src/views/Import.vue
Afin de ne plus oublier des logs de debug, on ajoute une regle eslint
On regle les erreurs actuelles
- Certains logs sont valides, on peut utiliser `console.error` ou désactiver la regle selon le besoin
- On supprime les logs qui ne servent à rien en production
=> feat: Add no-console eslint rule

src/style/main.css
certaines personnes qui ont la police Basic (`Source Sans Pro`) en local ne voient pas le gras dans les textes
la raison est que le css leur fait prendre leur version locale de "Source Sans pro" sans es variantes grasses.
On oblige tous les utilisateurs à télécharger la police de caractères
=> fix: Disallow local font

src/charts/charts.js, src/components/comparison/ComparisonDefaultCell.vue, src/components/comparison/ComparisonEconomics.vue, src/components/comparison/ComparisonEnvironment.vue, src/components/comparison/ComparisonExpandableRow.vue, src/components/comparison/ComparisonRow.vue, src/components/study/inclusiveness/NetOperatingProfitPerActor.vue, src/utils/data/metrics/eco/employment.js, src/utils/data/metrics/eco/netOperatingProfitPerActor.js, src/utils/data/metrics/index.js
Resolves #110
Après les retours utilisateurs, on a remarqu" que la page de comparaison pouvait etre mieux présentée
- Les couleurs vert/rouge ne permettent pas de comparaison
- Les indicateurs économiques ne sont pas les bons à présenter pour avoir le plus d'impact
- Pour comparer l'acv, il faut utiliser des Pt, et pas les untiés spécifiques
cf #110 pour la spec. Quelques textes ont été communiqués sur Teams par Marion
- Refacto (3 commits): Passer le netOperatingProfitPerActor dans les metrics afin d'y acceder dans la page de comparaison
- :one: Passer toutes les cellules de comparaison (outre le social) en bleu
- :two: Refondre les indicateurs économiques
- On réordonne / supprime l'existant (On change l'unité du gini index également)
- On ajoute 2 dropdown (jobs et net operating profit …
=> feat(110): Revise comparison indicators

src/views/HomeView.vue
Resolves #118 
| - | - | 
| ![image](https://github.com/user-attachments/assets/dd4027fe-985a-41c4-b48f-ce203e4b95f7) | ![image](https://github.com/user-attachments/assets/2fac97e9-abef-40b3-a6c0-4d2a69155cde) |
Notes:
J'ai copié collé le css du bouton de la page de comparaison, pour ne pas s'embeter à factoriser les deux boutons (un qui va vers un lien, un autre qui déclenche une action).
=> feat(118): Separate Browse and compare sections on the home page

src/components/study/inclusiveness/ShareOfFarmPrice.vue
Resolves #120
On affiche les produits dans la même cellule que le prix dans "Share of Farm price"
| - | - | 
| ![image](https://github.com/user-attachments/assets/936da5a4-99df-4f5b-a494-b319dfed4c87) | ![image](https://github.com/user-attachments/assets/9b523edc-1304-4037-b15c-125e4e3e0b2c) |
=> feat(120): Better display the Share of farm price table

src/components/StudyOverview.vue, src/components/comparison/ComparisonRow.vue, src/components/comparison/ComparisonTitle.vue
Resolves: #124 
- Déplacement du Sankey
- Retrait de la taille de police spécifique pour les titres des comparaisons (ex `Macro economic indicators`)
Le bout de la spec "padding" est en fait un problème de zoom que j'avais vu chez Léa dans la page de comparaison, j'ai noté ça dans la tache "petits écrans": https://www.notion.so/le-basic/S-adapter-aux-petits-crans-1056afc9ad64806aa235c5d6fccda172
=> feat(124): Some tweaks for comparison page + bring up Sankey

src/components/study/LocalStudyBanner.vue, src/utils/misc.js, src/views/Import.vue, src/views/StudyView.vue
Resolves #122 
On veut attirer l'attention des clients qui importent des données que ces données ne sont présentes qu'en local
On affiche donc la banière suivante
- Sur la page d'import (quand on a un import fait)
- Sur les pages de l'étude importée
- Création de la bannière + affichage dans les bonnes pages
- Emission d'un event pour supprimer l'étude en question dans les 2 composants parents
=> feat(122): Add banner to warn about local study status

src/components/Modal.vue, src/components/Skeleton.vue, src/components/comparison/StudiesListTable.vue, src/components/home/ByCategory.vue, src/components/home/ByContinent.vue, src/components/home/SubCardsList.vue, src/components/study/LocalStudyBanner.vue, src/components/study/StudyHeader.vue, src/style/tooltips-override.scss, src/views/Comparison.vue
Resolves #128
Lors des interviews utilisatrices, on a remarqué que certaisn écrans étaient petits / les navigateurs étaient zoomés par défaut (150%)
Cela demande quelques ajustements pour que le contenu s'affiche correctement
- :one: Limiter la hauteur de la modale de la page de comparaison pour que le bouton soit bien visible
- :two: Utilisation du nouveau dropdown floating-vue pour les sous-cartes de la page d'études (quand on a plusieurs études sur un meme pays/produit). 
- :three: Adaptation responsive de la bannière de #122 
- :four: Ajout d'une marge minimum en bas du rectange gris qui dit "Pas d'études selectionnée" en page de comparaison (100% cosmetique)
=> fix(128): adapt several pages to small screens

src/components/StudiesComparison.vue, src/components/comparison/ComparisonDefaultCell.vue, src/components/comparison/ComparisonEconomics.vue, src/components/comparison/ComparisonEnvironment.vue, src/components/comparison/ComparisonRow.vue
Ceci est l'intégration de 2 retours (quick-win) de Marion:
On veut distinguer les sous-cellules des parties économiques & environnementales, et on veut aussi rendre plus lisible
- Les cellules des sous rangs environnementaux et économiques ont une bordure bleue et un fond plus clair. Comme les sous-tags de la partie sociale
- On augmente la taille de police des cellules pour qu'elles aient la même taille que le reste du texte dans la page
| - | - | 
| ![image](https://github.com/user-attachments/assets/f8d3a741-cef1-41e1-8d09-480d1c7545f6) | ![image](https://github.com/user-attachments/assets/3466eeb3-9bf3-4a63-a7a3-0c07d8e84184) |
=> feat: Change comparion page default cells

src/components/StudyEnvironment.vue, src/components/comparison/comparisonConfig/environment.js, src/components/study/environment/ImpactDataviz.vue, src/utils/misc.js
Tache Notion (spec) : https://www.notion.so/le-basic/Ajouter-Global-warming-page-de-comparaison-1346afc9ad64800aae07cd14b7c71f64
On vaut ajouter deux rangs sous les indicateurs environnementaux en `pt` pour extraire le Global warming (en eq CO2)
- Un peu de boyscout
- Ajout des rows global warming (en refactorant un peu en meme temps: merge de 2 commits que j'avais fait à la base)
- :warning: Fix de l'algo qui calcule les impacts. Puisqu'on loopait sur les value chains, on tombait sur la value chain `Total production` (volume: total, impact: 0), ce qui divisait par deux l'impact réel par unité fonctionelle
- J'ai vérifié à la main les calculs, ça colle maintenant bien avec la page d'environnement (sur 2 études cashew)
=> feat: Add specific rows for Global warming on comparison page

src/charts/charts.js, src/components/comparison/comparisonConfig/economics.js, src/components/study/inclusiveness/NetOperatingProfit.vue, src/components/study/inclusiveness/NetOperatingProfitPerActor.vue, src/utils/data/metrics/eco/netOperatingProfit.js, src/utils/data/metrics/eco/netOperatingProfitPerActor.js, src/utils/data/metrics/index.js
https://www.notion.so/le-basic/Modif-indicateurs-co-Page-de-comparaison-13c6afc9ad6480958ca2f7a29e0ca9d9
Frédéric veut qu'on ajoute un rang avec le net operating profit
- Ajout du profit total des actors dans les métriques (et utilisation dans la page inclusivness)
- Utilisation de cette nouvelle clé dans les métriques pour ajouter le row
- EDIT: Déplacement de la ligne de value added (comme demandé en bonus dans la tache notion)
=> feat: Add global stage net operating profit in comparison

src/components/study/social-sustainability/SocialDetails.vue, src/components/study/social-sustainability/SocialRadar.vue, src/components/study/social-sustainability/SocialSummary.vue, src/components/study/social-sustainability/SummaryBlock.vue
La page sociale des études ne rends pas bien en petit écran, et il manque quelques informations pour bien la comprendre
- Rendre la grille avec les sommaires plus responsive, et ajouter les titres des axes afin de bien comprendre les correspondances
- Mise à jour des blocs de sommaires pour clarifier que les questions sont une sélection parmi plusieurs
- Changement du style des titres sur le détail pour bien comprendre que c'est un titre
=> Feat: Refactor Social sustainability page design
